defaults: # bigger sub-configurations to swap around
  - combo: ???
  - ls: ???
  - slurm: ???
  - phases: ???
  - _self_

wandb:
  project: 'test'
  entity: 'klx798949379'
  experiment_tag: 'test'

seeds:
  agent: 44 # seed for first agent of a configuration
  ls: 123 # seed for configuration sampler
  eval: 456 # seed for eval env

num_confs: ??? # number of landscape samples, needs to be power of 2 when using Sobol ls sampler
num_seeds: ??? # seed for agents and environments
