---
env_name: Gym-v0
workspace: table
engine: pybullet
render: opengl
camera: 0
ee_camera: 0
gui: 1
visualize: 0
visgym: 0
robot: kuka_push
robot_action: step
robot_init:
- 0
- 0.4
- 0.6
max_velocity: 10
max_force: 200
action_repeat: 1
task_type: reach
task_objects:
- init:
    obj_name: 'null'
  goal:
    obj_name: cube_holes
    fixed: 1
    rand_rot: 0
    sampling_area:
    - -0.5
    - 0.2
    - 0.3
    - 0.6
    - 0.1
    - 0.4
used_objects:
  num_range:
  - 0
  - 0
  obj_list: []
observation:
  actual_state: obj_xyz
  goal_state: obj_xyz
  additional_obs:
  - endeff_xyz
distractors:
  list:
  moveable: 1
  constant_speed: 0
  movement_dims: 3
  movement_endpoints:
  - -0.3
  - 0.3
  - 0.4
  - 0.7
  - 0.1
  - 0.3
reward: distance
distance_type: euclidean
vae_path:
yolact_path:
yolact_config:
train_framework: tensorflow
algo: ppo2
num_networks: 1
max_episode_steps: 1024
algo_steps: 1024
steps: 100000
pretrained_model:
multiprocessing: false
eval_freq: 10000
eval_episodes: 5
logdir: trained_models/reach
record: 0
