---
env_name: Gym-v0
workspace: table
engine: pybullet
render: opengl
camera: 0
ee_camera: 0
gui: 1
visualize: 0
visgym: 0
robot: ned2
robot_action: joints
robot_init:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
max_velocity: 10
max_force: 200
action_repeat: 100
task_type: push
task_objects:
- init:
    obj_name: cube
    fixed: 0
    rand_rot: 0
    sampling_area:
    - -0.2
    - 0.2
    - 0.15
    - 0.40
    - 0.011
    - 0.011
  goal:
    obj_name: target
    fixed: 1
    rand_rot: 0
    sampling_area:
    - -0.2
    - 0.2
    - 0.15
    - 0.40
    - 0.011
    - 0.011
used_objects:
  num_range:
  - 0
  - 0
  obj_list: []
observation:
  actual_state: obj_xyz
  goal_state: obj_xyz
  additional_obs:
  - endeff_xyz
distractors:
  list:
  moveable: 0
  constant_speed: 0
  movement_dims: 0
  movement_endpoints:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
reward: push
distance_type: euclidean
vae_path:
yolact_path:
yolact_config:
train_framework: pytorch
algo: sac
num_networks: 1
max_episode_steps: 100
algo_steps: 100
steps: 300000
pretrained_model: 
multiprocessing: false
eval_freq: 10000
eval_episodes: 5
train_test: 1
logdir: trained_models/push
record: 0